apiVersion: v1
kind: Pod
metadata:
  name: task1-pod
  labels:
    app: task1
spec:
  containers:
  - name: task1-container
    image: vamsichamarthi/devops-app:v2
    ports:
    - containerPort: 8080
